In [8]:
import pandas as pd
import json as json
from sodapy import Socrata

client = Socrata("data.cityofchicago.org", 
                 "o5qU1IxOMy5FwwEf8MWwOz5TY",
                 username="michelle.goldberg@gmail.com",
                 password="3rpNdTQ!fuHGAx4")

results = client.get("yhhz-zm2v", limit=4000)

                 
results_df = pd.DataFrame.from_records(results)
results_df

,zip_code,week_number,week_start,week_end,tests_weekly,tests_cumulative,test_rate_weekly,test_rate_cumulative,percent_tested_positive_weekly,percent_tested_positive_cumulative,...,zip_code_location,:@computed_region_rpca_8um6,:@computed_region_vrxf_vc4k,:@computed_region_6mkv_f3dw,:@computed_region_bdys_3d7i,:@computed_region_43wa_7qmu,cases_weekly,cases_cumulative,case_rate_weekly,case_rate_cumulative
0,60603,10,2020-03-01T00:00:00.000,2020-03-07T00:00:00.000,0,0,0,0,0.000,0.000,...,"{'type': 'Point', 'coordinates': [-87.625473, ...",34,38,14311,367,36,NaN,NaN,NaN,NaN
1,60603,11,2020-03-08T00:00:00.000,2020-03-14T00:00:00.000,0,0,0,0,0.000,0.000,...,"{'type': 'Point', 'coordinates': [-87.625473, ...",34,38,14311,367,36,NaN,NaN,NaN,NaN
2,60603,12,2020-03-15T00:00:00.000,2020-03-21T00:00:00.000,1,1,85.2,85.2,0.000,0.000,...,"{'type': 'Point', 'coordinates': [-87.625473, ...",34,38,14311,367,36,NaN,NaN,NaN,NaN
3,60603,13,2020-03-22T00:00:00.000,2020-03-28T00:00:00.000,3,4,255.5,340.7,0.000,0.000,...,"{'type': 'Point', 'coordinates': [-87.625473, ...",34,38,14311,367,36,NaN,NaN,NaN,NaN
4,60603,14,2020-03-29T00:00:00.000,2020-04-04T00:00:00.000,6,10,511.1,851.8,0.000,0.000,...,"{'type': 'Point', 'coordinates': [-87.625473, ...",34,38,14311,367,36,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3295,60640,3,2021-01-17T00:00:00.000,2021-01-23T00:00:00.000,3382,80463,4851.2,115417.1,0.028,0.048,...,"{'type': 'Point', 'coordinates': [-87.662232, ...",15,31,22616,633,18,89,3823,127.7,5483.8
3296,60666,45,2020-11-01T00:00:00.000,2020-11-07T00:00:00.000,0,0,0,0,0.000,0.000,...,"{'type': 'Point', 'coordinates': [-87.896371, ...",38,75,16197,668,29,NaN,NaN,NaN,NaN
3297,60620,22,2020-05-24T00:00:00.000,2020-05-30T00:00:00.000,892,6317,1309.9,9276.6,0.061,0.17,...,"{'type': 'Point', 'coordinates': [-87.651656, ...",59,70,21554,530,13,53,1066,77.8,1565.4
3298,60621,16,2020-04-12T00:00:00.000,2020-04-18T00:00:00.000,168,586,578.5,2017.8,0.399,0.353,...,"{'type': 'Point', 'coordinates': [-87.638812, ...",11,66,21559,435,4,76,219,261.7,754.1
3299,60630,35,2020-08-23T00:00:00.000,2020-08-29T00:00:00.000,991,14529,1728.2,25336.6,0.062,0.088,...,"{'type': 'Point', 'coordinates': [-87.759611, ...",48,11,21869,129,50,51,1162,88.9,2026.4

In [ ]:
#drop "unknown" from zip code
#create heatmap

In [4]:
## data type and data structure
print(pd)
print(type(pd))

<module 'pandas' from '/Users/michellegoldberg/opt/anaconda3/lib/python3.8/site-packages/pandas/__init__.py'>
<class 'module'>